apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: p48wuk0v7-go-gitops
  description: This is GitOps manifest for p48wuk0v7-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: p48wuk0v7-go
    janus-idp.io/tekton: p48wuk0v7-go
    backstage.io/kubernetes-id: p48wuk0v7-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:p48wuk0v7-go
